[package]
name = "day-05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
itertools = "0.12.0"
nom = "7.1.3"
nom-supreme = "0.8.0"
rayon = "1.8.0"
regex = "1.10.2"
